import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Dashboard from "./components/layout/dashboard";
import Panel from "./components/layout/panel";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <div className="grid grid-cols-12">
              
              <header className="col-span-12">
                <Dashboard />
              </header>

              <aside className="col-span-2">
                <Panel></Panel>
              </aside>

              <main className="col-span-10">
                {children}
              </main>
              
            </div>  
      </body>
    </html>
  );
}
